import React, { useState } from 'react';
import { 
  View, 
  Text, 
  StyleSheet, 
  Image, 
  ScrollView, 
  TouchableOpacity,
  StatusBar,
  SafeAreaView
} from 'react-native';
import { FontAwesomeIcon } from '@fortawesome/react-native-fontawesome';
import { faArrowLeft, faCheckCircle, faClock } from '@fortawesome/free-solid-svg-icons';
import { useTheme } from '../../context/ThemeContext';
import { useNavigation, useRoute } from '@react-navigation/native';

const ArticleDetailScreen = () => {
  const { theme } = useTheme();
  const { colors } = theme;
  const navigation = useNavigation();
  const route = useRoute();
  
  // Extract article data passed from Explore screen
  const { article } = route.params || {};

  if (!article) return null;

  return (
    <SafeAreaView style={[styles.safeArea, { backgroundColor: colors.background }]}>
      <StatusBar barStyle={theme.dark ? "light-content" : "dark-content"} />
      
      {/* ── Fixed Header ── */}
      <View style={[styles.header, { backgroundColor: colors.background }]}>
        <TouchableOpacity 
          style={styles.backButton} 
          onPress={() => navigation.goBack()}
          hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
        >
          <FontAwesomeIcon icon={faArrowLeft} size={20} color={colors.text} />
        </TouchableOpacity>
        <Text style={[styles.headerTitle, { color: colors.text }]}>Article</Text>
        <View style={styles.headerRight} />
      </View>

      <ScrollView 
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.scrollContent}
      >
        {/* ── Hero Image ── */}
        <View style={styles.imageContainer}>
          <Image 
            source={{ uri: article.imageUrl || article.image }} 
            style={styles.image}
            resizeMode="cover"
          />
          <View style={styles.imageOverlay}>
            <View style={[styles.categoryBadge, { backgroundColor: colors.primary }]}>
              <Text style={styles.categoryText}>{article.category || 'General'}</Text>
            </View>
          </View>
        </View>

        {/* ── Content ── */}
        <View style={styles.contentContainer}>
          <Text style={[styles.title, { color: colors.text }]}>
            {article.title}
          </Text>

          <View style={styles.metaRow}>
            <View style={styles.metaItem}>
              <FontAwesomeIcon icon={faClock} size={14} color={colors.textSecondary || '#888'} />
              <Text style={[styles.metaText, { color: colors.textSecondary || '#888' }]}>
                1 min read
              </Text>
            </View>
            <View style={styles.metaItem}>
              <FontAwesomeIcon icon={faCheckCircle} size={14} color={article.isRead ? colors.primary : (colors.textSecondary || '#888')} />
              <Text style={[styles.metaText, { color: article.isRead ? colors.primary : (colors.textSecondary || '#888') }]}>
                {article.isRead ? "Read" : "Unread"}
              </Text>
            </View>
          </View>

          <View style={[styles.divider, { backgroundColor: colors.border || '#333' }]} />

          <Text style={[styles.bodyText, { color: colors.text }]}>
            {article.content}
          </Text>

          {/* AI Disclaimer or Extra Info */}
          <View style={[styles.aiDisclaimer, { backgroundColor: colors.card, borderColor: colors.border || '#333' }]}>
            <Text style={[styles.aiText, { color: colors.textSecondary || '#aaa' }]}>
              ✨ This personalized learning content was generated by AI based on your goals and preferences to help you grow today.
            </Text>
          </View>

        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
    zIndex: 10,
  },
  backButton: {
    padding: 5,
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: 'RedditSans-SemiBold',
  },
  headerRight: {
    width: 30, // to balance the flex space with back button
  },
  scrollContent: {
    paddingBottom: 40,
  },
  imageContainer: {
    width: '100%',
    height: 250,
    position: 'relative',
  },
  image: {
    width: '100%',
    height: '100%',
  },
  imageOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    alignItems: 'flex-start',
    padding: 20,
    backgroundColor: 'rgba(0,0,0,0.1)', // Subtle gradient/darken effect could go here
  },
  categoryBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  categoryText: {
    color: '#fff',
    fontSize: 12,
    fontFamily: 'RedditSans-Bold',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  contentContainer: {
    padding: 24,
  },
  title: {
    fontSize: 26,
    fontFamily: 'RedditSans-Bold',
    lineHeight: 34,
    marginBottom: 16,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
    marginBottom: 20,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  metaText: {
    fontSize: 14,
    fontFamily: 'RedditSans-Medium',
  },
  divider: {
    height: 1,
    width: '100%',
    marginBottom: 24,
    opacity: 0.5,
  },
  bodyText: {
    fontSize: 16,
    fontFamily: 'RedditSans-Regular',
    lineHeight: 28,
    marginBottom: 30,
  },
  aiDisclaimer: {
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    marginTop: 20,
  },
  aiText: {
    fontSize: 13,
    fontFamily: 'RedditSans-Regular',
    lineHeight: 20,
    fontStyle: 'italic',
  }
});

export default ArticleDetailScreen;
